# Generated by Django 4.1.7 on 2023-03-04 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('logo', models.ImageField(upload_to='cat_img/')),
                ('state', models.CharField(max_length=300)),
                ('vision', models.TextField()),
                ('description', models.TextField()),
                ('founding_year', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('manage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
