# Generated by Django 4.1.7 on 2023-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_ngodetails_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngodetails',
            name='logo',
            field=models.ImageField(upload_to='my_img'),
        ),
    ]
