# Generated by Django 4.1.7 on 2023-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_ngodetails_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='my_img')),
                ('imge2', models.ImageField(upload_to='my_img')),
                ('title1', models.CharField(max_length=300)),
                ('title2', models.CharField(max_length=300)),
                ('desc', models.TextField()),
            ],
        ),
    ]
