# Generated by Django 4.1.7 on 2023-03-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0004_blog_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='manage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog_model',
            name='ngo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='track.ngodetails'),
        ),
    ]
