# Generated by Django 4.1.7 on 2023-03-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='desc',
            new_name='desc2',
        ),
    ]
