# Generated by Django 4.1.7 on 2023-03-04 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0007_rename_desc_achievement_desc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='desc_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1', models.ImageField(upload_to='my_img')),
                ('img2', models.ImageField(upload_to='my_img')),
                ('title1', models.CharField(max_length=300)),
                ('title2', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('manage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='track.ngodetails')),
            ],
        ),
        migrations.CreateModel(
            name='achievement_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='my_img')),
                ('img2', models.ImageField(upload_to='my_img')),
                ('t1', models.CharField(max_length=300)),
                ('t2', models.CharField(max_length=300)),
                ('desc2', models.TextField()),
                ('manage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='track.ngodetails')),
            ],
        ),
    ]
