# Generated by Django 4.1.7 on 2023-03-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_desc_model_achievement_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement_model',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='achievement_model',
            name='t2',
        ),
    ]
